version: "{build}"

services: mssql2014

environment:
  matrix:
    - nodejs_version: "0.10"
    - nodejs_version: "0.12"
    - nodejs_version: "4"
    - nodejs_version: "5"
    - nodejs_version: "6"

branches:
  only:
  - master

install:
  - ps: Install-Product node $env:nodejs_version
  - cmd: npm install

services:
  - mssql2017

cache: node_modules
build: off

before_test:
  - npm prune

test_script:
  - cmd: npm test
